name: mylibrary
description: "A Digital Library project."
publish_to: 'none'
version: 0.1.1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2  
  flutter_secure_storage: ^9.2.4
  # Google Fonts
  google_fonts: ^6.2.0

  # Firebase Dependencies (Latest Stable Versions)
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.5
  firebase_storage: ^11.6.6


  # Charts for Graphs & Data Visualization
  fl_chart: ^0.66.0  

  # Google Sign-In
  google_sign_in: ^6.2.1  
  share_plus: 10.0.0
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.2
  image_picker: ^1.1.2      # For picking images from gallery/camera
  image_cropper: ^5.0.1
  flutter_image_compress: ^2.1.0
  flutter_launcher_icons: ^0.14.3
  lottie: ^2.3.2  # Check for the latest version
  timeago: ^3.7.0
  flutter_animate: ^4.1.0  # Use the latest version
  dio: ^5.8.0+1
  flutter_spinkit: ^5.2.1
  cached_network_image: ^3.3.1  # Add this line





dev_dependencies:
  flutter_launcher_icons: ^0.14.3

  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/logo/logo.png
    - assets/images/pattern.png
    - assets/animations/loading.json  # ✅ Add this line

 
    
  fonts:
   - family: Poppins
     fonts:
       - asset: assets/fonts/Poppins-Regular.ttf
       - asset: assets/fonts/Poppins-Bold.ttf
         weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"
  adaptive_icon_background: "#ffffff"  # Background color
  adaptive_icon_foreground: "assets/logo/logo.png"